defaults:
  - _self_
  - data
  - wandb


NUM_CLASSES: 200
BATCH_SIZE: 512
VAL_EVERY_N_EPOCH: 1

NUM_EPOCHS: 100

OPTIMIZER_PARAMS:
  type: SGD
  lr: 0.005
  momentum: 0.9

SCHEDULER_PARAMS:
  type: MultiStepLR
  milestones: [30, 35]
  gamma: 0.2

MODEL_NAME: alexnet

ACCELERATOR: gpu
DEVICES: [0]
PRECISION_STR: 32-true